name: Update Coverage Badge

on:
  workflow_run:
    workflows: [".NET"]
    types:
      - completed

jobs:
  update-badge:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Download coverage report artifact
        uses: dawidd6/action-download-artifact@v3
        with:
          workflow: dotnet.yml
          name: code-coverage-report
          path: coverage-report
          
      - name: Extract coverage percentage
        id: extract-coverage
        run: |
          COVERAGE=$(grep -o 'Line coverage.*[0-9]\+%' coverage-report/index.html | grep -o '[0-9]\+%' | head -1 | tr -d '%')
          echo "coverage=$COVERAGE" >> $GITHUB_OUTPUT
          
      - name: Create the coverage badge JSON
        run: |
          mkdir -p .github/badges
          cat > .github/badges/coverage.json << EOF
          {
            "schemaVersion": 1,
            "label": "coverage",
            "message": "${{ steps.extract-coverage.outputs.coverage }}%",
            "color": "$([ ${{ steps.extract-coverage.outputs.coverage }} -ge 90 ] && echo 'brightgreen' || ([ ${{ steps.extract-coverage.outputs.coverage }} -ge 80 ] && echo 'green' || ([ ${{ steps.extract-coverage.outputs.coverage }} -ge 70 ] && echo 'yellowgreen' || ([ ${{ steps.extract-coverage.outputs.coverage }} -ge 60 ] && echo 'yellow' || ([ ${{ steps.extract-coverage.outputs.coverage }} -ge 50 ] && echo 'orange' || echo 'red')))))"
          }
          EOF
          
      - name: Create Gist for badge
        uses: exuanbo/actions-deploy-gist@v1
        with:
          token: ${{ secrets.GIST_TOKEN }}
          gist_id: ${{ secrets.GIST_ID }}
          file_path: .github/badges/coverage.json
          file_type: json
          file_name: coverage.json
